name: Publish Grand Highlanders

on:
  push:
    branches:
      - main

jobs:
  publish-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t toyota-inventory .

    - name: Run Docker container to generate artifacts
      run: |
        mkdir -p artifacts
        docker run --rm \
          -e MODEL=grandhighlanderhybrid \
          -e ZIPCODE=97086 \
          -e DISTANCE=250 \
          -e CSV=/root/artifacts/inventory.csv \
          -e JSON=/root/artifacts/inventory.json \
          -v "$(pwd)/artifacts:/root/artifacts" \
          toyota-inventory

    - name: Upload artifacts as gists
      env:
        GITHUB_GIST_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
      run: |
        gist_id="d75b56bab416b36d118d07bbd6134c17"
        gist_file_name="inventory.json"

        # Upload files
        curl -X PATCH "https://api.github.com/gists/$gist_id" \
          -H "Authorization: token $GITHUB_GIST_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "files": {
              "inventory.json": {
                "content": "'"$(cat $(pwd)/artifacts/inventory.json)"'"
              },
              "inventory.csv": {
                "content": "'"$(cat $(pwd)/artifacts/inventory.csv)"'"
              }
            }
          }'
