name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t toyota-inventory:latest .

    - name: Push Docker Image
      run: |
        docker push rtomac/toyota-inventory:latest
